### ISSUE TITLE
Demo运行后，直播延迟非常严重

### ISSUE THREAD

**Issue by hq3595** [qiniudemo/qiniu-live-iOS#2]
下载了Demo，并运行成功
iPhone6手机端进行直播，电脑上用Safari浏览器输入m3u8地址观看直播
发现电脑上延迟很严重，大概有二十秒左右
降低了码率还是一样
请问这是Demo版服务器端的问题 还是我这边客户端的参数需要其他调整？

**Comment by Kivenhaoyu** [comment]
请检查你的网络，并且更新版本，目前这个只是一个demo版本，请勿做他用
